services:
  kafka:
    image: apache/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1 
      KAFKA_PROCESS_ROLES: broker,controller 
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093" 
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092" 
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER 
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093" 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - example-net
    post_start:
      - command: "./kafka-topics.sh --bootstrap-server localhost:9092 --create --topic test-topic"
        working_dir: /opt/kafka/bin
    healthcheck:
      test: "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1"
      start_period: 20s

  lumu-producer:
    build: ./producer/backend/
    container_name: producer
    ports:
      - "7000:7000"
    environment:
      KAFKA_SERVER: "kafka:9092"
      KAFKA_TOPIC: "test-topic"
    networks:
      - example-net
    depends_on:
      - kafka

  lumu-consumer:
    build: ./consumer/backend/
    container_name: consumer1
    ports:
      - "8000:8000"
    environment:
      NODES_NETWORK: "10.0.0.0/24"
      DISCOVERING_INTERVAL: 10
      KAFKA_SERVER: "kafka:9092"
      KAFKA_TOPIC: "test-topic"
    networks:
      - example-net
    depends_on:
      - kafka


networks:
  example-net:
    name: example-net
    ipam:
      config:
        - subnet: 10.0.0.0/24

